# Generated by Django 5.2.7 on 2025-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='business_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='chain_of_custody',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='communication_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='compliance_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='data_privacy_impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='discovery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='encryption_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='escalation_level',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='evidence_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='external_references',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='geo_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='impact_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='insurance_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='interview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='investigation_methods',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='last_qa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='legal_holds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='lessons_learned',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='notification_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='peer_review_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='quality_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recovery_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='related_cases',
            field=models.ManyToManyField(blank=True, to='cases.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='risk_level',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='security_level',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='statute_limitations',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='success_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='witnesses',
            field=models.TextField(blank=True),
        ),
    ]
