# Generated by Django 5.0 on 2025-11-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_budget_allocated_case_business_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='analysis_category_confidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_filing_authorities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_filing_viability',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_legal_sections',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_pincode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_sanction_recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
