# Generated by Django 4.2.7 on 2025-11-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_analysis_category_confidence_case_analysis_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='analysis_evidence_priority',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_next_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='analysis_timeline_estimate',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
