# Generated by Django 4.2.7 on 2025-11-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_analysis_evidence_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='apprehension_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='evidence_collected',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='follow_up_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_sequence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='medical_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='stolen_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='suspect_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='witnesses_info',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
