# Generated by Django 5.0 on 2025-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_apprehension_info_case_evidence_collected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='accused_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='area_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='city_district',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='case',
            name='complainant_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='evidence_catalog',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='fir_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='motive',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='officer_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='case',
            name='place_occurrence',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='police_station_jurisdiction',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='case',
            name='remarks_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reporting_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='seized_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
